CREATE TABLE IF NOT EXISTS BOOKS (
id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
TITLE TEXT,
YEAR_OF_PUBLICATION INTEGER,
PUBLISHER_ID INTEGER,
SUBJECT TEXT
FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHERS(PUBLISHER_ID)
);

CREATE TABLE IF NOT EXISTS AUTHORS (
AUTHOR_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
NAME TEXT
);

CREATE TABLE IF NOT EXISTS BOOKAUTHORS (
BOOK_ID INTEGER NOT NULL,
AUTHOR_ID INTEGER NOT NULL,
AUTHOR_ORDER INTEGER NOT NULL,
FOREIGN KEY(BOOK_ID) REFERENCES BOOKS(id),
FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);

CREATE TABLE IF NOT EXISTS PUBLISHERS (
PUBLISHER_ID INTEGER NOT NULL PRIMARY KEY,
PUBLISHER_NAME TEXT
);